# Generated by Django 5.0.6 on 2024-05-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exhibits", "0002_exhibithomeindex"),
    ]

    operations = [
        migrations.AddField(
            model_name="exhibithome",
            name="exhibit_display_order",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
