# Generated by Django 5.0.6 on 2024-09-24 19:26

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exhibits", "0002_generalpage_alter_exhibithome_image"),
        ("wagtailcore", "0093_uploadedfile"),
        ("wagtailimages", "0026_delete_uploadedimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exhibithome",
            name="hero_cta",
            field=models.CharField(
                blank=True,
                help_text="Entry text for the exhibit landing page.",
                max_length=255,
                verbose_name="Enter the exhibit text",
            ),
        ),
        migrations.AlterField(
            model_name="exhibithome",
            name="hero_text",
            field=models.TextField(
                blank=True,
                help_text="An introduction to the exhibit.",
                max_length=355,
                verbose_name="Introductory text",
            ),
        ),
        migrations.AlterField(
            model_name="exhibithomeindex",
            name="intro",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="An index page for all the exhibits."
            ),
        ),
        migrations.CreateModel(
            name="ExhibitPageImageOneThird",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("body", wagtail.fields.RichTextField(blank=True)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "link_to_next_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "link_to_previous_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
