# Generated by Django 5.0.6 on 2024-09-24 19:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exhibits", "0003_alter_exhibithome_hero_cta_and_more"),
        ("wagtailcore", "0093_uploadedfile"),
        ("wagtailimages", "0026_delete_uploadedimage"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ExhibitPageImageOneThird",
            new_name="ExhibitPageImageOneThirdLeft",
        ),
    ]
