# Generated by Django 5.0.6 on 2024-09-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "exhibits",
            "0004_rename_exhibitpageimageonethird_exhibitpageimageonethirdleft",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="exhibitpageimageonethirdleft",
            name="is_end_of_exhibit",
            field=models.BooleanField(default=False),
        ),
    ]
