# Generated by Django 5.0.6 on 2024-09-24 19:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exhibits", "0005_exhibitpageimageonethirdleft_is_end_of_exhibit"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExhibitPageImageOneThirdLeft",
        ),
    ]
