# Generated by Django 5.0.6 on 2024-09-25 18:24

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exhibits", "0013_exhibithome_next_page_exhibithome_previous_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="exhibithome",
            name="image_caption",
            field=models.CharField(
                blank=True,
                help_text="Caption for the exhibit landing page image.",
                max_length=500,
                verbose_name="Image caption",
            ),
        ),
        migrations.AddField(
            model_name="exhibitpagehalfandhalf",
            name="image_caption",
            field=models.CharField(
                blank=True,
                help_text="Caption for the exhibit landing page image.",
                max_length=500,
                verbose_name="Image caption",
            ),
        ),
        migrations.AddField(
            model_name="exhibitpageleftimageonethird",
            name="image_caption",
            field=models.CharField(
                blank=True,
                help_text="Caption for the exhibit landing page image.",
                max_length=500,
                verbose_name="Image caption",
            ),
        ),
        migrations.AddField(
            model_name="exhibitpagerightimageonethird",
            name="image_caption",
            field=models.CharField(
                blank=True,
                help_text="Caption for the exhibit landing page image.",
                max_length=500,
                verbose_name="Image caption",
            ),
        ),
        migrations.AddField(
            model_name="imagecomparison",
            name="first_image_caption",
            field=models.CharField(
                blank=True,
                help_text="Caption for the first image.",
                max_length=500,
                verbose_name="Image caption",
            ),
        ),
        migrations.AddField(
            model_name="imagecomparison",
            name="second_image_caption",
            field=models.CharField(
                blank=True,
                help_text="Caption for the second image.",
                max_length=500,
                verbose_name="Image caption for the second image",
            ),
        ),
        migrations.AlterField(
            model_name="exhibithome",
            name="body",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Optional additional text for the exhibit landing page.",
            ),
        ),
        migrations.AlterField(
            model_name="exhibithome",
            name="hero_text",
            field=models.TextField(
                blank=True,
                help_text="An introduction to the exhibit.",
                max_length=355,
                verbose_name="Entry button text",
            ),
        ),
    ]
