# Generated by Django 5.0.6 on 2024-09-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exhibits", "0014_exhibithome_image_caption_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exhibithome",
            name="is_chapter_intro_page",
            field=models.BooleanField(
                default=False,
                help_text="Is this the first page of a chapter? If checked, yes.",
            ),
        ),
        migrations.AddField(
            model_name="exhibitpagehalfandhalf",
            name="is_chapter_intro_page",
            field=models.BooleanField(
                default=False,
                help_text="Is this the first page of a chapter? If checked, yes.",
            ),
        ),
        migrations.AddField(
            model_name="exhibitpageleftimageonethird",
            name="is_chapter_intro_page",
            field=models.BooleanField(
                default=False,
                help_text="Is this the first page of a chapter? If checked, yes.",
            ),
        ),
        migrations.AddField(
            model_name="exhibitpagerightimageonethird",
            name="is_chapter_intro_page",
            field=models.BooleanField(
                default=False,
                help_text="Is this the first page of a chapter? If checked, yes.",
            ),
        ),
    ]
