# Generated by Django 5.0.6 on 2024-09-26 17:12

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exhibits", "0015_exhibithome_is_chapter_intro_page_and_more"),
        ("wagtailcore", "0093_uploadedfile"),
        ("wagtailimages", "0026_delete_uploadedimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExhibitPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "layout",
                    models.CharField(
                        choices=[
                            ("left_image_one_third", "Left Image, One Third"),
                            ("right_image_one_third", "Right Image, One Third"),
                            ("left_image_two_thirds", "Left Image, Two Thirds"),
                            ("right_image_two_thirds", "Right Image, Two Thirds"),
                            ("half_and_half", "Half and Half"),
                            ("full_screen", "Full Screen"),
                            ("wide_image", "Wide Image"),
                            ("comparison_image", "Comparison Image"),
                        ],
                        default="left_image_one_third",
                        help_text="Select the layout for this exhibit page.",
                        max_length=22,
                    ),
                ),
                (
                    "image_caption",
                    models.CharField(
                        blank=True,
                        help_text="Caption for the exhibit page image.",
                        max_length=500,
                        verbose_name="Image caption",
                    ),
                ),
                ("body", wagtail.fields.RichTextField(blank=True)),
                (
                    "is_end_of_exhibit",
                    models.BooleanField(
                        default=False,
                        help_text="Is this the last page of the exhibit? If checked, yes.",
                    ),
                ),
                (
                    "is_chapter_intro_page",
                    models.BooleanField(
                        default=False,
                        help_text="Is this the first page of a chapter? If checked, yes.",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        help_text="Image for the exhibit page.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "link_to_next_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "link_to_previous_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
