# Generated by Django 5.0.6 on 2024-09-26 17:47

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exhibits", "0016_exhibitpage"),
        ("wagtailimages", "0026_delete_uploadedimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagecomparison",
            name="first_image",
            field=models.ForeignKey(
                help_text="First image to compare",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="imagecomparison",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image_comparisons",
                to="exhibits.exhibitpage",
            ),
        ),
        migrations.AlterField(
            model_name="imagecomparison",
            name="second_image",
            field=models.ForeignKey(
                help_text="Second image to compare",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
