# Generated by Django 5.0.6 on 2024-09-26 18:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exhibits", "0017_alter_imagecomparison_first_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exhibitpageleftimageonethird",
            name="image",
        ),
        migrations.RemoveField(
            model_name="exhibitpageleftimageonethird",
            name="link_to_next_page",
        ),
        migrations.RemoveField(
            model_name="exhibitpageleftimageonethird",
            name="link_to_previous_page",
        ),
        migrations.RemoveField(
            model_name="exhibitpageleftimageonethird",
            name="page_ptr",
        ),
        migrations.RemoveField(
            model_name="exhibitpagerightimageonethird",
            name="image",
        ),
        migrations.RemoveField(
            model_name="exhibitpagerightimageonethird",
            name="link_to_next_page",
        ),
        migrations.RemoveField(
            model_name="exhibitpagerightimageonethird",
            name="link_to_previous_page",
        ),
        migrations.RemoveField(
            model_name="exhibitpagerightimageonethird",
            name="page_ptr",
        ),
        migrations.DeleteModel(
            name="ExhibitPageHalfAndHalf",
        ),
        migrations.DeleteModel(
            name="ExhibitPageLeftImageOneThird",
        ),
        migrations.DeleteModel(
            name="ExhibitPageRightImageOneThird",
        ),
    ]
