# Generated by Django 5.0.6 on 2024-09-26 18:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exhibits", "0018_remove_exhibitpageleftimageonethird_image_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExhibitHomeIndex",
        ),
    ]
