# Generated by Django 5.0.6 on 2024-09-26 20:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exhibits", "0021_exhibithomeindex_delete_exhibitindex"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exhibitpage",
            name="is_chapter_intro_page",
        ),
        migrations.RemoveField(
            model_name="exhibitpage",
            name="is_end_of_exhibit",
        ),
    ]
