# Generated by Django 5.0.6 on 2024-09-26 20:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exhibits", "0022_remove_exhibitpage_is_chapter_intro_page_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExhibitHomeIndex",
        ),
    ]
