# Generated by Django 5.0.6 on 2024-10-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exhibits", "0024_exhibitpage_display_title_alter_exhibitpage_layout"),
    ]

    operations = [
        migrations.AddField(
            model_name="exhibitpage",
            name="image_zoomable",
            field=models.BooleanField(
                default=False,
                help_text="Check this box if you want the image to be zoomable.",
            ),
        ),
    ]
