# Generated by Django 5.0.6 on 2024-10-02 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exhibits", "0025_exhibitpage_image_zoomable"),
        ("wagtailimages", "0026_delete_uploadedimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="exhibitpage",
            name="image_first_column",
            field=models.ForeignKey(
                blank=True,
                help_text="First image for three-column layouts.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="exhibitpage",
            name="image_second_column",
            field=models.ForeignKey(
                blank=True,
                help_text="Second image for three-column layouts.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="exhibitpage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image for the exhibit page.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="exhibitpage",
            name="image_caption",
            field=models.CharField(
                blank=True,
                help_text="Use this field for single column or two-column layouts.",
                max_length=500,
                verbose_name="Image caption",
            ),
        ),
    ]
