# Generated by Django 5.0.6 on 2024-10-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exhibits", "0026_exhibitpage_image_first_column_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exhibitpage",
            name="image_first_column_caption",
            field=models.CharField(
                blank=True,
                help_text="Caption for the first image.",
                max_length=500,
                verbose_name="Image caption",
            ),
        ),
        migrations.AddField(
            model_name="exhibitpage",
            name="image_second_column_caption",
            field=models.CharField(
                blank=True,
                help_text="Caption for the second image.",
                max_length=500,
                verbose_name="Image caption",
            ),
        ),
        migrations.AlterField(
            model_name="exhibitpage",
            name="layout",
            field=models.CharField(
                choices=[
                    ("left_image_one_third", "Left Image, One Third"),
                    ("right_image_one_third", "Right Image, One Third"),
                    ("left_image_two_thirds", "Left Image, Two Thirds"),
                    ("right_image_two_thirds", "Right Image, Two Thirds"),
                    ("three_column_images_left", "Three Column, Images on Left"),
                    ("three_column_images_right", "Three Column, Images on Right"),
                    ("half_and_half", "Half and Half"),
                    ("full_screen", "Full Screen"),
                    ("wide_image", "Wide Image"),
                ],
                default="left_image_one_third",
                help_text="Select the layout for this exhibit page.",
                max_length=25,
            ),
        ),
    ]
