# Generated by Django 5.0.6 on 2024-10-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exhibits", "0028_exhibitpage_link_to_subsection"),
    ]

    operations = [
        migrations.AddField(
            model_name="exhibitpage",
            name="image_first_column_zoomable",
            field=models.BooleanField(
                default=False,
                help_text="Check this box if you want the first image to be zoomable.",
                verbose_name="Enable zoom for first image",
            ),
        ),
        migrations.AddField(
            model_name="exhibitpage",
            name="image_second_column_zoomable",
            field=models.BooleanField(
                default=False,
                help_text="Check this box if you want the second image to be zoomable.",
                verbose_name="Enable zoom for second image",
            ),
        ),
        migrations.AlterField(
            model_name="exhibitpage",
            name="image_zoomable",
            field=models.BooleanField(
                default=False,
                help_text="Check this box if you want the image to be zoomable.",
                verbose_name="Enable zoom for image",
            ),
        ),
    ]
