# Generated by Django 5.1.6 on 2025-04-15 18:31

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exhibits", "0030_generalpagethreecolumn"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeAboutSnippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title for the about section", max_length=255
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        help_text="Subtitle for the about section",
                        max_length=255,
                    ),
                ),
                (
                    "content",
                    wagtail.fields.RichTextField(
                        help_text="The main content of the about section"
                    ),
                ),
            ],
            options={
                "verbose_name": "Home Page About Text",
                "verbose_name_plural": "Home Page About Texts",
            },
        ),
    ]
