# Generated by Django 5.1.6 on 2025-02-20 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("material", "0008_alter_textilerecord_archive"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StagedMuseumItem",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=500)),
                ("date", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("item_type", models.CharField(max_length=100)),
                ("medium", models.CharField(max_length=100)),
                ("url", models.URLField()),
                ("country", models.CharField(max_length=100)),
                ("archive", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("api_response", models.JSONField()),
                ("is_reviewed", models.BooleanField(default=False)),
                ("review_notes", models.TextField(blank=True)),
                ("published", models.BooleanField(default=False)),
                (
                    "published_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staged_source",
                        to="material.textilerecord",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "connthreads_staged_items",
                "permissions": [
                    ("can_review_items", "Can review staged items"),
                    ("can_publish_items", "Can publish items to production"),
                ],
            },
        ),
    ]
