# Generated by Django 5.1.6 on 2025-02-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stagedmuseumitem",
            old_name="timestamp",
            new_name="initial_date_fetched",
        ),
        migrations.AddField(
            model_name="stagedmuseumitem",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="stagedmuseumitem",
            name="archive",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="stagedmuseumitem",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="stagedmuseumitem",
            name="date",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="stagedmuseumitem",
            name="item_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="stagedmuseumitem",
            name="medium",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
