# Generated by Django 5.1.6 on 2025-11-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "crawler",
            "0002_rename_timestamp_stagedmuseumitem_initial_date_fetched_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="stagedmuseumitem",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="staged_items/",
                verbose_name="Downloaded Image",
            ),
        ),
        migrations.AlterField(
            model_name="stagedmuseumitem",
            name="id",
            field=models.CharField(
                max_length=100, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="stagedmuseumitem",
            name="url",
            field=models.URLField(verbose_name="URL"),
        ),
    ]
