# Generated by Django 5.1.6 on 2025-05-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "crawler",
            "0002_rename_timestamp_stagedmuseumitem_initial_date_fetched_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="stagedmuseumitem",
            name="manifest",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="stagedmuseumitem",
            name="thumbnail",
            field=models.URLField(blank=True, default=""),
        ),
    ]
