# Generated by Django 5.1.6 on 2025-11-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0003_stagedmuseumitem_image_alter_stagedmuseumitem_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stagedmuseumitem",
            name="manifest",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="stagedmuseumitem",
            name="thumbnail",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="stagedmuseumitem",
            name="is_reviewed",
            field=models.BooleanField(default=False, verbose_name="Item reviewed?"),
        ),
        migrations.AlterField(
            model_name="stagedmuseumitem",
            name="published",
            field=models.BooleanField(default=False, verbose_name="Item published?"),
        ),
    ]
