# Generated by Django 5.0.6 on 2024-09-18 20:43

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        default="Unnamed Area", max_length=255, unique=True
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PrimaryTextileType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SecondaryTextileType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=350, null=True, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "city",
                    models.CharField(
                        default="Unnamed City", max_length=765, unique=True
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=765, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="places",
                        to="material.area",
                    ),
                ),
            ],
            options={
                "ordering": ["city"],
                "unique_together": {("city", "area")},
            },
        ),
        migrations.CreateModel(
            name="PlacesAlias",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("alias", models.CharField(max_length=765, unique=True)),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="place_aliases",
                        to="material.place",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TextileAlias",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("alias", models.CharField(max_length=765, unique=True)),
                (
                    "textile_record_primary",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="primary_alias",
                        to="material.primarytextiletype",
                    ),
                ),
                (
                    "textile_record_secondary",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secondary_alias",
                        to="material.secondarytextiletype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Textile Aliases",
            },
        ),
        migrations.CreateModel(
            name="TextileRecord",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField(blank=True, null=True)),
                (
                    "textile_specifications",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "circulation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("td", "Trade & Distribution"),
                            ("pr", "Production"),
                            ("co", "Consumption"),
                        ],
                        null=True,
                    ),
                ),
                ("summary_of_record", models.TextField(blank=True, null=True)),
                ("transcription", models.TextField(blank=True, null=True)),
                ("price", models.CharField(blank=True, max_length=350, null=True)),
                ("currency", models.CharField(blank=True, max_length=765, null=True)),
                (
                    "source_type",
                    models.CharField(blank=True, max_length=765, null=True),
                ),
                ("description_of_source", models.TextField(blank=True, null=True)),
                (
                    "record_creator",
                    models.CharField(blank=True, max_length=765, null=True),
                ),
                (
                    "source_reference",
                    models.CharField(blank=True, max_length=765, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crosslinks",
                    models.ManyToManyField(blank=True, to="material.textilerecord"),
                ),
                (
                    "from_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_textile_records",
                        to="material.area",
                    ),
                ),
                (
                    "from_place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_textile_records",
                        to="material.place",
                    ),
                ),
                (
                    "keywords",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "primary_subjects",
                    models.ManyToManyField(
                        blank=True,
                        related_name="primary_subject_records",
                        to="material.subject",
                    ),
                ),
                (
                    "primary_textile_types",
                    models.ManyToManyField(
                        blank=True,
                        default=[],
                        related_name="textile_records",
                        to="material.primarytextiletype",
                    ),
                ),
                (
                    "secondary_subjects",
                    models.ManyToManyField(
                        blank=True,
                        related_name="secondary_subject_records",
                        to="material.subject",
                    ),
                ),
                (
                    "secondary_textile_types",
                    models.ManyToManyField(
                        blank=True,
                        default=[],
                        related_name="textile_records",
                        to="material.secondarytextiletype",
                    ),
                ),
                (
                    "to_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_textile_records",
                        to="material.area",
                    ),
                ),
                (
                    "to_place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_textile_records",
                        to="material.place",
                    ),
                ),
            ],
            options={
                "ordering": ["year"],
            },
        ),
        migrations.CreateModel(
            name="NamedActor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "textile_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="named_actors",
                        to="material.textilerecord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.ImageField(upload_to="images/")),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("caption", models.CharField(blank=True, max_length=500, null=True)),
                ("alt_text", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "is_image_public",
                    models.BooleanField(
                        default=False, help_text="Can this image be publicly viewable?"
                    ),
                ),
                (
                    "image_rights_documentation",
                    models.FileField(blank=True, null=True, upload_to="documentation/"),
                ),
                (
                    "textile_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="material.textilerecord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArchivalRecord",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "archival_reference",
                    models.CharField(
                        blank=True,
                        help_text="The archival citation of a source.",
                        max_length=765,
                        null=True,
                    ),
                ),
                (
                    "source_reference",
                    models.CharField(
                        blank=True,
                        help_text="The bibliographic citation of a source.",
                        max_length=765,
                        null=True,
                    ),
                ),
                ("document", models.FileField(upload_to="media/records/")),
                (
                    "textile_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archival_records",
                        to="material.textilerecord",
                    ),
                ),
            ],
        ),
    ]
