# Generated by Django 5.0.6 on 2024-06-11 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="places",
                        to="material.area",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TextileRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "associated_textile",
                    models.CharField(
                        choices=[
                            ("Madras", "Madras"),
                            ("Pulicat", "Pulicat"),
                            ("Gingham", "Gingham"),
                        ],
                        max_length=50,
                    ),
                ),
                ("terminology_specific_info", models.TextField()),
                ("production_consumption_distribution", models.TextField()),
                ("summary_other", models.TextField()),
                ("summary_for_publication", models.TextField()),
                ("transcription", models.TextField()),
                ("quantitative_data", models.BooleanField()),
                ("quantitative_excerpt", models.TextField(blank=True, null=True)),
                ("currency", models.CharField(max_length=50)),
                ("associated_name", models.CharField(max_length=100)),
                ("source_type", models.CharField(max_length=100)),
                ("description_of_source", models.TextField()),
                ("producer_other", models.TextField()),
                ("source_reference", models.CharField(max_length=100)),
                (
                    "from_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_textile_records",
                        to="material.area",
                    ),
                ),
                (
                    "from_place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_textile_records",
                        to="material.place",
                    ),
                ),
                (
                    "primary_subjects",
                    models.ManyToManyField(
                        related_name="primary_subject_records", to="material.subject"
                    ),
                ),
                (
                    "secondary_subjects",
                    models.ManyToManyField(
                        related_name="secondary_subject_records", to="material.subject"
                    ),
                ),
                (
                    "to_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_textile_records",
                        to="material.area",
                    ),
                ),
                (
                    "to_place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_textile_records",
                        to="material.place",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "textile_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="material.textilerecord",
                    ),
                ),
            ],
        ),
    ]
