# Generated by Django 5.0.6 on 2024-06-11 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textilerecord",
            name="associated_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="textilerecord",
            name="associated_textile",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Madras", "Madras"),
                    ("Pulicat", "Pulicat"),
                    ("Gingham", "Gingham"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="textilerecord",
            name="currency",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="textilerecord",
            name="description_of_source",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="textilerecord",
            name="from_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_textile_records",
                to="material.area",
            ),
        ),
        migrations.AlterField(
            model_name="textilerecord",
            name="from_place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_textile_records",
                to="material.place",
            ),
        ),
        migrations.AlterField(
            model_name="textilerecord",
            name="primary_subjects",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="primary_subject_records",
                to="material.subject",
            ),
        ),
        migrations.AlterField(
            model_name="textilerecord",
            name="producer_other",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="textilerecord",
            name="production_consumption_distribution",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="textilerecord",
            name="quantitative_data",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="textilerecord",
            name="secondary_subjects",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="secondary_subject_records",
                to="material.subject",
            ),
        ),
        migrations.AlterField(
            model_name="textilerecord",
            name="source_reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="textilerecord",
            name="source_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="textilerecord",
            name="summary_for_publication",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="textilerecord",
            name="summary_other",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="textilerecord",
            name="terminology_specific_info",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="textilerecord",
            name="to_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_textile_records",
                to="material.area",
            ),
        ),
        migrations.AlterField(
            model_name="textilerecord",
            name="to_place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_textile_records",
                to="material.place",
            ),
        ),
        migrations.AlterField(
            model_name="textilerecord",
            name="transcription",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="textilerecord",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
