# Generated by Django 5.0.6 on 2024-09-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="textilerecord",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
