# Generated by Django 5.0.6 on 2024-09-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0002_textilerecord_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="textilerecord",
            name="creator",
            field=models.CharField(
                blank=True,
                choices=[
                    ("user", "User"),
                    ("admin", "Admin"),
                    ("crawler", "Web Crawler"),
                ],
                max_length=350,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="textilerecord",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="Check this box if the record is publicly viewable. Unchecked will keep the record hidden.",
            ),
        ),
    ]
