# Generated by Django 5.0.6 on 2024-06-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0003_alter_textilerecord_primary_subjects_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="city",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="place",
            name="country",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(max_length=350, unique=True),
        ),
        migrations.AlterField(
            model_name="textilerecord",
            name="associated_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="textilerecord",
            name="source_reference",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="textilerecord",
            name="source_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
