# Generated by Django 5.0.6 on 2024-06-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0004_alter_place_city_alter_place_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="city",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="place",
            name="country",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="textilerecord",
            name="associated_name",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="textilerecord",
            name="source_reference",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="textilerecord",
            name="source_type",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
