# Generated by Django 5.0.6 on 2024-10-08 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0006_alter_textilerecord_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textilerecord",
            name="archive",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="textile_records",
                to="material.archivalrecord",
            ),
        ),
    ]
