# Generated by Django 5.0.6 on 2024-10-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0007_alter_textilerecord_archive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textilerecord",
            name="archive",
            field=models.CharField(blank=True, max_length=765, null=True),
        ),
    ]
