# Generated by Django 5.1.6 on 2025-11-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("material", "0008_alter_textilerecord_archive"),
    ]

    operations = [
        migrations.AddField(
            model_name="textilerecord",
            name="id_manual",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
