# Generated by Django 5.1.6 on 2025-05-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0008_alter_textilerecord_archive"),
    ]

    operations = [
        migrations.AddField(
            model_name="textilerecord",
            name="manifest_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="textilerecord",
            name="thumbnail_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
