# Generated by Django 5.0.6 on 2024-06-11 20:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0009_alter_place_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="place",
            unique_together={("city", "area")},
        ),
    ]
