# Generated by Django 5.1.6 on 2025-11-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0009_textilerecord_id_manual"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textilerecord",
            name="id_manual",
            field=models.IntegerField(blank=True, null=True, verbose_name="Record ID"),
        ),
    ]
