# Generated by Django 5.1.6 on 2025-12-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("material", "0010_alter_textilerecord_id_manual"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textilerecord",
            name="id_manual",
            field=models.CharField(blank=True, null=True, verbose_name="Record ID"),
        ),
    ]
