# Generated by Django 5.0.6 on 2024-06-11 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0010_alter_place_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="places",
                to="material.area",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="city",
            field=models.CharField(blank=True, max_length=765, null=True),
        ),
        migrations.AlterField(
            model_name="place",
            name="country",
            field=models.CharField(blank=True, max_length=765, null=True),
        ),
    ]
