# Generated by Django 5.1.6 on 2025-12-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0011_alter_textilerecord_id_manual"),
    ]

    operations = [
        migrations.CreateModel(
            name="TextileType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="textilerecord",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="Database ID"
            ),
        ),
        migrations.AddField(
            model_name="textilerecord",
            name="textile_type",
            field=models.ManyToManyField(
                blank=True, related_name="textile_records", to="material.textiletype"
            ),
        ),
    ]
