# Generated by Django 5.0.6 on 2024-06-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0011_alter_place_area_alter_place_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="city",
            field=models.CharField(blank=True, max_length=765, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="place",
            name="country",
            field=models.CharField(blank=True, max_length=765, null=True, unique=True),
        ),
    ]
