# Generated by Django 5.0.6 on 2024-06-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0013_alter_textilerecord_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="area",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="image",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="subject",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
