# Generated by Django 5.0.6 on 2024-07-09 13:41

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0014_alter_area_id_alter_image_id_alter_subject_id"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="textilerecord",
            old_name="summary_other",
            new_name="summary_of_record",
        ),
        migrations.RemoveField(
            model_name="textilerecord",
            name="associated_name",
        ),
        migrations.RemoveField(
            model_name="textilerecord",
            name="associated_textile",
        ),
        migrations.RemoveField(
            model_name="textilerecord",
            name="producer_other",
        ),
        migrations.RemoveField(
            model_name="textilerecord",
            name="production_consumption_distribution",
        ),
        migrations.RemoveField(
            model_name="textilerecord",
            name="quantitative_data",
        ),
        migrations.RemoveField(
            model_name="textilerecord",
            name="quantitative_excerpt",
        ),
        migrations.RemoveField(
            model_name="textilerecord",
            name="summary_for_publication",
        ),
        migrations.RemoveField(
            model_name="textilerecord",
            name="terminology_specific_info",
        ),
        migrations.AddField(
            model_name="image",
            name="image_rights_documentation",
            field=models.FileField(
                blank=True, null=True, upload_to="image_rights_documentation/"
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="is_image_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="textilerecord",
            name="circulation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("td", "Trade & Distribution"),
                    ("pr", "Production"),
                    ("co", "Consumption"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="textilerecord",
            name="crosslinks",
            field=models.ManyToManyField(blank=True, to="material.textilerecord"),
        ),
        migrations.AddField(
            model_name="textilerecord",
            name="keywords",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="textilerecord",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="textilerecord",
            name="record_creator",
            field=models.CharField(blank=True, max_length=765, null=True),
        ),
        migrations.AddField(
            model_name="textilerecord",
            name="textile_specifications",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to="media/images/"),
        ),
        migrations.AlterField(
            model_name="textilerecord",
            name="currency",
            field=models.CharField(blank=True, max_length=765, null=True),
        ),
        migrations.CreateModel(
            name="NamedActor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "textile_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="named_actors",
                        to="material.textilerecord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TextileSubtype",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "textile_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="textile_subtype",
                        to="material.textilerecord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TextileType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "textile_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="textile_type",
                        to="material.textilerecord",
                    ),
                ),
            ],
        ),
    ]
