# Generated by Django 5.0.6 on 2024-07-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "material",
            "0015_rename_summary_other_textilerecord_summary_of_record_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="caption",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="description",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
