# Generated by Django 5.0.6 on 2024-07-09 14:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0016_image_caption_alter_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="textilerecord",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="textilerecord",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="is_image_public",
            field=models.BooleanField(
                default=False, help_text="Can this image be publicly viewable?"
            ),
        ),
    ]
