# Generated by Django 5.0.6 on 2024-07-09 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0017_textilerecord_created_at_textilerecord_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="textiletype",
            name="textile_type_selection",
            field=models.CharField(
                blank=True,
                choices=[("pr", "Primary"), ("se", "Secondary")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ArchivalRecord",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "archival_reference",
                    models.CharField(
                        help_text="The archival citation of a source.",
                        max_length=765,
                        unique=True,
                    ),
                ),
                (
                    "source_reference",
                    models.CharField(
                        blank=True,
                        help_text="The bibliographic citation of a source.",
                        max_length=765,
                        null=True,
                    ),
                ),
                ("document", models.FileField(upload_to="media/records/")),
                (
                    "textile_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archival_records",
                        to="material.textilerecord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlacesAlias",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("alias", models.CharField(max_length=765, unique=True)),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="place_aliases",
                        to="material.place",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TextileAlias",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("alias", models.CharField(max_length=765, unique=True)),
                (
                    "textile_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="material.textiletype",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="TextileSubtype",
        ),
    ]
