# Generated by Django 5.0.6 on 2024-07-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0018_textiletype_textile_type_selection_archivalrecord_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="textilealias",
            options={"verbose_name_plural": "Textile Aliases"},
        ),
        migrations.AlterField(
            model_name="archivalrecord",
            name="archival_reference",
            field=models.CharField(
                blank=True,
                help_text="The archival citation of a source.",
                max_length=765,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="textiletype",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Notes"),
        ),
    ]
