# Generated by Django 5.0.6 on 2024-07-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0022_remove_textiletype_textile_record_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="area",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
