# Generated by Django 5.0.6 on 2024-07-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0025_alter_subject_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="country",
            field=models.CharField(blank=True, max_length=765, null=True),
        ),
    ]
