# Generated by Django 5.0.6 on 2024-07-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0026_alter_place_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(blank=True, max_length=350, null=True, unique=True),
        ),
    ]
