# Generated by Django 5.0.6 on 2024-07-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0027_alter_subject_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="area",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
