# Generated by Django 5.0.6 on 2024-07-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0028_alter_area_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
