# Generated by Django 5.0.6 on 2024-07-11 15:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0029_place_latitude_place_longitude"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="area",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="place",
            options={"ordering": ["city"]},
        ),
        migrations.AlterModelOptions(
            name="textilerecord",
            options={"ordering": ["year"]},
        ),
        migrations.AlterModelOptions(
            name="textiletype",
            options={"ordering": ["name"]},
        ),
    ]
