# Generated by Django 5.0.6 on 2024-07-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0030_alter_area_options_alter_place_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="alt_text",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
