# Generated by Django 5.0.6 on 2024-07-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0031_image_alt_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to="media/"),
        ),
    ]
