# Generated by Django 5.0.6 on 2024-08-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0032_alter_image_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="area",
            name="name",
            field=models.CharField(default="Unnamed Area", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="image",
            name="image_rights_documentation",
            field=models.FileField(blank=True, null=True, upload_to="documentation/"),
        ),
        migrations.AlterField(
            model_name="place",
            name="city",
            field=models.CharField(default="Unnamed City", max_length=765, unique=True),
        ),
    ]
