# Generated by Django 5.0.6 on 2024-09-05 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0033_alter_area_name_alter_image_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrimaryTextileType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SecondaryTextileType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="textilealias",
            name="textile_record",
        ),
        migrations.RemoveField(
            model_name="textilerecord",
            name="textile_types",
        ),
        migrations.AddField(
            model_name="textilealias",
            name="textile_record_primary",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="primary_alias",
                to="material.primarytextiletype",
            ),
        ),
        migrations.AddField(
            model_name="textilerecord",
            name="primary_textile_types",
            field=models.ManyToManyField(
                blank=True,
                default=[],
                related_name="textile_records",
                to="material.primarytextiletype",
            ),
        ),
        migrations.AddField(
            model_name="textilealias",
            name="textile_record_secondary",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="secondary_alias",
                to="material.secondarytextiletype",
            ),
        ),
        migrations.AddField(
            model_name="textilerecord",
            name="secondary_textile_types",
            field=models.ManyToManyField(
                blank=True,
                default=[],
                related_name="textile_records",
                to="material.secondarytextiletype",
            ),
        ),
        migrations.DeleteModel(
            name="TextileType",
        ),
    ]
